/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PkoAmbulanceWlList {
    }
}
declare global {
    interface HTMLPkoAmbulanceWlListElement extends Components.PkoAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLPkoAmbulanceWlListElement: {
        prototype: HTMLPkoAmbulanceWlListElement;
        new (): HTMLPkoAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "pko-ambulance-wl-list": HTMLPkoAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface PkoAmbulanceWlList {
    }
    interface IntrinsicElements {
        "pko-ambulance-wl-list": PkoAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pko-ambulance-wl-list": LocalJSX.PkoAmbulanceWlList & JSXBase.HTMLAttributes<HTMLPkoAmbulanceWlListElement>;
        }
    }
}
